server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://mongodb:Sarthak_2001@microservicecluster.dmrx9.mongodb.net/
#      uri: mongodb://localhost:27017
      database: microservices
  config:
    import: optional:configserver:http://localhost:8085
    #spring: config: import: configserver:http://localhost:8085     || This can also be used

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka