server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Sarthak_2001
    driver-class-name: com.mysql.cj.jdbc.Driver
#    dialect: org.hibernate.dialect.MYSQL8Dialect
  config:
    import: optional:configserver:http://localhost:8085
    #spring: config: import: configserver:http://localhost:8085     || This can also be used
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#spring:
#  profiles:
#    active: prod //This is to directly change the configuration file on GitHub from project

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 3
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelRetry:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

