server:
  port: 8086

spring:
  application:
    name: IDENTITY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Sarthak_2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    dialect: org.hibernate.dialect.MYSQL8Dialect
  config:
    import: optional:configserver:http://localhost:8085
    #spring: config: import: configserver:http://localhost:8085     || This can also be used
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: "user"
      password: "pass"